# Generated by Django 2.0.4 on 2018-10-06 04:16

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlelikes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlelikes',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.AddField(
            model_name='articlelikes',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2018, 10, 6, 4, 16, 57, 896055, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlelikes',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
