# Generated by Django 2.0.4 on 2018-10-08 06:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_auto_20181006_0416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleLikes',
            new_name='ArticleLike',
        ),
    ]
